[build]
  command = "npm run build"
  publish = "build"

# Proxy das chamadas /api para o Render
[[redirects]]
  from = "/api/*"
  to = "https://seu-app.onrender.com/api/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
