# Generated by Django 4.2.24 on 2025-09-30 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.tweet'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='social_user_set', related_query_name='social_user', to='auth.group', verbose_name='groups'),
        ),
    ]
